export enum tagTypes {
  user = "user",
  super_admin = "super_admin",
  admin = "admin",
  seller = "seller",
  sells_manager = "sells_manager",
  customer = "customer",
  category = "category",
  shop = "shop",
  product = "product",
  sku = "sku",
  color = "color",
  size = "size",
  tags = "tags",
  coupon = "coupon",
  cart = "cart",
  orders = "orders",
  payment="payment",
}

export const tagTypesList = [
  tagTypes.super_admin,
  tagTypes.admin,
  tagTypes.seller,
  tagTypes.sells_manager,
  tagTypes.customer,
  tagTypes.category,
  tagTypes.shop,
  tagTypes.product,
  tagTypes.sku,
  tagTypes.color,
  tagTypes.size,
  tagTypes.tags,
  tagTypes.coupon,
  tagTypes.cart,
  tagTypes.orders,
  tagTypes.payment
];
